### ISSUE TITLE
create-react-native-starter script

### ISSUE THREAD

**Issue by birkir** [ueno-llc/react-native-starter#13]
Maybe a good idea to make a module to create react-native-starter quickly via global npm command.

**Comment by Salakar** [comment]
In the context of this issue I might have something that would interest you,

It's still very much a **WIP** and would like to get some early testers/feedback but.. I'm working on a `react-native-firebase` CLI:

### Planned CLI Features

Features below are what I'm working on for the initial release. Post release I'd like to work on more advanced features such as **creating new RN + FB projects based off templates and configuring them**, configuring installed Firebase modules, project inspector (scan project code against a known set of common misconfiguration scenarios) to help highlight any issues - things such as that.

#### CLI Internals

- Supports non immersive - i.e. just run a command directly with all args
- Supports immersive interactivity
   - Interactive prompts for all args if arg not pre-populated e.g. choose a project from a list to view it's apps
   - Full auto complete support (some early examples in gifs below).
- Fast, I mean really fast
   - built-in smart data fetching (fetch ahead / eager fetching)
   - smart caching

#### Firebase Console
- Multiple accounts supported by default with easy/quick switching
- Create/View/Delete  **projects**
- Create/View/Delete **apps** 
- Download/Install app **sdk configuration files**:
     - **ios** (GoogleService-Info.plist)
     - **android** (google-services.json)
     - **web** (json with code example)
     - [**rnfb-dynamic-apps** config](https://rnfirebase.io/docs/v3.3.x/core/initialize-apps#Cross-Platform-Example) (code snippet with populated **iosConfig** & **androidConfig** objects)
     - **admin-sdk** (service-account.json)
- Retrieve FCM server token

#### React Native

 - rename the current projects bundle identifier/package names
    - if RNFB project prompt to swap out Firebase plist/json sdk configs to match new names

#### React Native Firebase

 - install Firebase SDK credential plist & json files
   - automatically finds the correct configs across all Firebase accounts based on bundle identifier/package names
       - if no existing apps found on Firebase prompt to create new ones
 - quick swap out existing Firebase SDK credential plist & json files
   - example use case would be using different configs/apps per environment

----

### Early Previews 

These are far from the finished product, they're just to give you an idea of how it's working/going 🙈

#### Navigating around and demonstrating auto complete, firebase apis and account switching:
![cli-usage](https://cdn.discordapp.com/attachments/362972933921964032/422300777407709184/2018-03-11_07.48.56.gif) 

----

#### Add an account process - this is only needs doing once per account, just like the Official Firebase CLI:
![auth](https://cdn.discordapp.com/attachments/362972933921964032/422444659751780373/2018-03-11_17.23.20.gif)
