### ISSUE TITLE
react-native-ui-lib view components

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/react-native-starter#135]
I'd rather we didn't use the react-native-ui-lib components for views. They have some great components like `TagsInput` and all that cool stuff that I think is fine, but the `<View flex paddingH-25 paddingT-120>` is a bit too much like Bootstrap or Tachyons.

https://github.com/ueno-llc/react-native-starter/blob/c78e6b449a7601ac8fff774b3e7fc643af17c819/src/screens/splash/Splash.js#L26

**Comment by birkir** [comment]
Sure, they also have an awful bug where changes to props don't hot reload or react to prop changes dynamically...

Disaster, but I liked the idea of being able to have no stylesheet in some components. I understand it's like tachyons which I hate in a cascading environment, but this is different.

**Comment by elliottkember** [comment]
> changes to props don't hot reload or react to prop changes dynamically

yikes!

I do think the idea of no-stylesheet is nice, but I also think we'd end up with a mix of prop-styles and style={} attributes which is awkward. I'd prefer to have all the style code in one place, even if that means styles for each component.

**Comment by birkir** [comment]
Okay, I've used it for some time and mixing style={} with the props is not awkward at all. It's very clear what is happening.

The system is themable too, so we can define shared styles, colors, fonts and such, I recommend reading upon it or try it before you discard it.

The props are computed into stylesheet blob on construction, hence closer to stylesheet than inline styles.

I find it very useful when creating container component that has to be flex and nothing else. No stylesheet or inline styles. I think it's pretty fair use.

I am up for debate, but I'm not completely sold on it too.

**Comment by elliottkember** [comment]
For separation of concerns, I'd want to keep the style of an element separate to the template structure. It's convenient to add attributes to the JSX, but that's not where they belong - `flex` prop is like writing out `style={{ flex: 1 }}`. Style properties belong in the `StyleSheet`.

I'm not saying this is a slippery slope, but we also don't want to end up here:

```
      <View flex paddingH-25 paddingT-120>
        <Text blue50 text20>Welcome</Text>
        <TextInput text50 placeholder="username" dark10/>
        <TextInput text50 placeholder="password" secureTextEntry dark10/>
        <View marginT-100 center>
          <Button text70 white background-orange30 label="Login"/>
          <Button link text70 orange30 label="Sign Up" marginT-20/>
        </View>
      </View>
```
