### ISSUE TITLE
Why include fastlane certs in the main repo?

### ISSUE THREAD

**Issue by isaachinman** [ueno-llc/react-native-starter#169]
I notice you have included `Matchfile`s in both the android and ios fastlane dirs.

I am new to RN and am just getting set up with fastlane. Can you explain your reasoning here, when the [fastlane docs](https://docs.fastlane.tools/actions/match/) specifically recommend running `match` in a different "certificates" repo?

It seems like Bitrise already expects fastlane certs to be in a separate repo. Maybe you set it up this way to facilitate ease of use with Travis?

Will there be any serious problems with your CI/deployment setup if I pull my certs into a separate repo entirely?

**Comment by birkir** [comment]
The certs are in a different repository, which is private. I am not sure what you are talking about.
