### ISSUE TITLE
Upgrade to react-native-navigation v2?

### ISSUE THREAD

**Issue by isaachinman** [ueno-llc/react-native-starter#180]
So it seems like `react-native-navigation` v2 is finally stable enough to be officially recommended by the maintainers.

Just wondering if a PR to upgrade this repo to v2 would be accepted.

**Comment by birkir** [comment]
What is coming in next release:
 - App Center build steps with integrated CodePush deployment
 - 100% TypeScript codebase
 - react-native-navigation v2
 - react-native@0.56.0

Currently RNNv2 is not stable enough for android in react-native 0.56, I'll be waiting for a PR to be merged there. Not saying I am a maintainer, but I do contribute a lot into RNN.

I'll be streamlining react-native-config so it will be less prune to errors. Refactor rename script so it will be more stable. Include mobx-state-tree with some UI specific stuff I'd like to ship with by default.

**Comment by isaachinman** [comment]
Great to hear you already have an upgrade planned. An unsolicited thought: adding things like TypeScript and `mobx-state-tree` as defaults would make this starter kit _extremely_ opinionated. I get that it's primarily for internal use, but I think it would drive away some potential users.

Thanks again for maintaining a fantastic project!

**Comment by birkir** [comment]
Noted. Thanks Isaac.
