### ISSUE TITLE
fastlane tag_version failed in App Center Build

### ISSUE THREAD

**Issue by zhangtaii** [ueno-llc/react-native-starter#191]
**Related logs as below:**

[10:04:20]: ▸ [35mfatal: could not read Password for 'https://***@dev.azure.com': Device not configured[0m
+----------------------+---------------------+
|                [33mLane Context[0m                |
+----------------------+---------------------+
| DEFAULT_PLATFORM     | android             |
| PLATFORM_NAME        | android             |
| LANE_NAME            | android tag_version |
| ANDROID_VERSION_NAME | 1.0.1               |
| ANDROID_VERSION_CODE | 2                   |
+----------------------+---------------------+

**Comment by jeremybarbet** [comment]
As far as I understand you ran a build through App center and you got this issue. I can suggest you to look at the [guide here _newly edited_](https://ueno-llc.github.io/react-native-starter/#/PUBLISHING?id=configure-ios-or-android) to check if you didn't forget anything in your environnement variables.

**Comment by zhangtaii** [comment]
@jeremybarbet, thanks for your concern, the problem arise when fasltlane tries to interact with the remote git repo, but fails as no git credential configured in the building server. 
According to the **Docs**, seams no git credential exists in the ENV.
![image](https://user-images.githubusercontent.com/6049450/46956913-04a92d00-d0c9-11e8-8933-e13472c5ef72.png)

P.S. I'm using _Azure DevOps_ to host the git repo, if that could be the cause of the problem?

**Comment by birkir** [comment]
That could be the case. I haven't tried any other repository providers than GitHub.

Try raising an issue with AppCenter and see what they say. There is a trick to make this work with an ash-agent though (logging in to github as anyone you like), we had this for v1:

- https://github.com/ueno-llc/react-native-starter/blob/ed361e77e8b9d45f1fb0bbff8612b61aa5f7d6c1/.travis/build.sh#L9-21

**Comment by zhangtaii** [comment]
Thanks for the suggestion, I'll give it a try.

**Comment by jeremybarbet** [comment]
I close this issue, feel free to reopen it if needed!
