### ISSUE TITLE
xcodebuild on AppCenter not seeing env vars

### ISSUE THREAD

**Issue by andrejcesen** [ueno-llc/react-native-starter#193]
`xcodebuild` invoked by AppCenter doesn't seem to find environment variables set on AppCenter's Build UI page.

Specifically, Xcode can't seem to find env variable `SENTRY_AUTH_TOKEN`, which is used in `Bundle React Native code and images` step. Is there any way I can get a hold of it in the xcodebuild process?

**To Reproduce**
1. When iOS build comes into `Bundle React Native code and images` step, this piece of code is not executed (because `SENTRY_AUTH_TOKEN` is not set):
```sh
if [ ! -z "$SENTRY_AUTH_TOKEN" ]; then
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
else
```

**Expected behavior**
I would expect xcodebuild for it to pick it up. "works on my machine" :)

### Environment
* React Native Starter version: `2.0.0`
* React Native version: `0.57`

**Comment by jeremybarbet** [comment]
Sorry for the delay.

Have you been able to find the issue? if not here is some things to try out:

- Do you know if the others variables are recognized?
- Do you have `SENTRY_AUTH_TOKEN ` set into your .env file?
- Did you run `yarn build:env`?
- Make sure you completed all the steps here: https://ueno-llc.github.io/react-native-starter/#/PUBLISHING?id=_6-configure-app-center

**Comment by jeremybarbet** [comment]
I will close this issue, feel free to reopen it if needed
