### ISSUE TITLE
react-native run-ios CFBundleIdentifier Does Not Exist issue

### ISSUE THREAD

**Issue by daviswhitehead** [ueno-llc/react-native-starter#196]
FYI I had to modify my Workspace Build System settings to successfully run `react-native run-ios`. Was seeing the following issue.

```Installing build/Build/Products/Debug-iphonesimulator/foundation.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/foundation.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/foundation.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:575:11)
    at Object.execFileSync (child_process.js:593:13)
    at Promise.then (/Users/dwhitehead/Documents/github/react-native-starter/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>
```

Resolved it by doing the following
<img width="534" alt="screen shot 2018-11-23 at 09 26 26" src="https://user-images.githubusercontent.com/8632165/48948656-4072b600-ef03-11e8-9d02-c73bbb801bed.png">

<img width="514" alt="screen shot 2018-11-23 at 09 26 43" src="https://user-images.githubusercontent.com/8632165/48948661-46689700-ef03-11e8-9fc4-2a6ffaed06dd.png">

`react-native info`
```  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 301.08 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.7.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.2, 28.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.14 => 16.4.14
      @types/react-native: 0.57.1 => 0.57.1
      react: 16.5.2 => 16.5.2
      react-native: 0.57.2 => 0.57.2
```

Not sure how you want to update the documentation or repo to prevent this in the future, but happy to help if you'd like.

**Comment by jeremybarbet** [comment]
Hey!

You should be able to run the starter-kit without changing any workspace settings, however you've been able to find a workaround to keep working 👍🏻.

I would suggest you to try this following command and see it fixes the issue with the default settings

```bash
pod install --repo-update
# or if that fails for some reason like it did for me
pod repo remove master
pod setup
pod install # inside ios dir
```

**Comment by daviswhitehead** [comment]
¯\_(ツ)_/¯ I duno what to say. I followed the instructions exactly as written in the readme.

**Comment by jeremybarbet** [comment]
The documentation might be missing also steps to be able to run the starter-kit under all kind of setups, that's why your feedbacks are important.

- What's your setup right now? Do you still have the changes on your workspace settings?
- Did you the previous command I gave you?

**Comment by daviswhitehead** [comment]
I ran your commands and was unsuccessful but the xcode workspace setting changes did allow me to run the app.

**Comment by jeremybarbet** [comment]
Sorry for the delay.

Is your repo this one: https://github.com/daviswhitehead/react-native-starter If so, I've been to do `yarn start` and `react-native run-ios`.

It must be something related with your config. You can try to remove all the temp data from Xcode`rm -rf ~/Library/Developer/Xcode/DerivedData` and also do on the emulator "Hardware > Erase All Content and Settings".

**Comment by jeremybarbet** [comment]
I'm closing this issue. Let us know if you have more questions
