### ISSUE TITLE
Example of how to wire up Mobx State Tree with React Native Firebase (Cloud Firestore)

### ISSUE THREAD

**Issue by zachheine** [ueno-llc/react-native-starter#200]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but rather a request for an example on how to (good practice) wire up `mobx-state-tree` with `react-native-firebase`. 

**Describe the solution you'd like**
A medium complexity example that illustrates data syncing with Cloud Firestore.

**Describe alternatives you've considered**
I'm learning both MST and RN Firebase and I will eventually provide an example if I can, but I'm not there yet!

**Additional context**
None at the moment.

**Comment by jeremybarbet** [comment]
Hey!

Unfortunately, we don't have any available examples for this. You can look around for firestore and mobx (v1) solution and adapt it for MST.

https://hackernoon.com/a-useful-wrapper-for-mobx-and-firebase-cloud-firestore-3d9f3310ed23

**Comment by birkir** [comment]
Not the most simple example but should serve as a good reference point.

https://github.com/birkir/hekla/blob/master/src/stores/Stories.ts

**Comment by jeremybarbet** [comment]
I'll close this issue, hopefully it helped you in your research!
