### ISSUE TITLE
Android Code Push configuration bug?

### ISSUE THREAD

**Issue by dgobaud** [ueno-llc/react-native-starter#201]
Line 85 in `build.gradle` makes the apply of `codepush.gradle` dependent on `CODEPUSH_ACCESS_KEY` - seems like a bug. Don't see anything like this in the iOS builds and `CODEPUSH_ACCESS_KEY` is only used in the App Center deploy scripts. I think the conditional should be removed.

https://github.com/ueno-llc/react-native-starter/blob/master/android/app/build.gradle#L85
```
if (project.env.get('CODEPUSH_ACCESS_KEY') != '') {
  apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
}
```

**Comment by jeremybarbet** [comment]
As far as I know, this is part of the installation from `react-native-code-push`: https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-android---manual

For iOS (https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods), the installation is here: https://github.com/ueno-llc/react-native-starter/blob/master/ios/Podfile#L7

**Comment by dgobaud** [comment]
I'm just saying remove the if `if (project.env.get('CODEPUSH_ACCESS_KEY') != '') {`

**Comment by birkir** [comment]
So you want to make CodePush required? I am not 100% up for that.

**Comment by dgobaud** [comment]
Yes I thought it was or it at least is for iOS? I guess if the idea is that it is actually optional then yes this should be left in.
