### ISSUE TITLE
Android project doesn't execute build-env.sh leading to stale environment variable values

### ISSUE THREAD

**Issue by dgobaud** [ueno-llc/react-native-starter#203]
The XCode project executes `build-env.sh` to make sure `config.env.js` is updated but the Android project doesn't seem to. Simple fix is to create a `yarn android` command eg `"android": "yarn build:env && react-native run-android"` but would be better to make the Android gradle projects execute `build-env.sh`

XCode link https://github.com/ueno-llc/react-native-starter/blob/master/ios/react-native-starter.xcodeproj/project.pbxproj#L100

**Comment by jeremybarbet** [comment]
Hey!

This is a good catch, it would be way better to have it in the android project. We will take a look at it!

**Comment by jeremybarbet** [comment]
Fixed with https://github.com/ueno-llc/react-native-starter/pull/210
