### ISSUE TITLE
Update existing project

### ISSUE THREAD

**Issue by Amurmurmur** [ueno-llc/react-native-starter#207]
How do you update a currently existing react-native-starter project to the latest version of the boilerplate or at least merge changes.

**Comment by jeremybarbet** [comment]
We don't have any update script to do it. But what we do is to have a remote pointing to this repository and fetching it to get latest updates.

You fetch and merge from upstream, and brace yourself for merge conflicts.
```
git remote add upstream git@github.com:ueno-llc/react-native-starter.git
git fetch upstream master
git merge upstream/master
```

**Comment by Amurmurmur** [comment]
@jeremybarbet Sweet thank you very much for your help.

Thats exactly what I was looking for.
