### ISSUE TITLE
configure sentry to upload iOS/Android native debug symbols

### ISSUE THREAD

**Issue by dgobaud** [ueno-llc/react-native-starter#214]
https://docs.sentry.io/clients/cocoa/dsym/

https://docs.sentry.io/clients/java/modules/android/

**Comment by jeremybarbet** [comment]
Do you mean you don't get any artifacts inside sentry? Did you check your logs to see if the symbols were uploaded?

**Comment by dgobaud** [comment]
JavaScript artifacts are uploaded but not the native ones.

JavaScript ones are uploaded here https://github.com/ueno-llc/react-native-starter/blob/master/appcenter-pre-build.sh#L56

**Comment by dgobaud** [comment]
That I think that uploads the React Native sourcemaps - not the native symbol files I'm talking about.

Looking here https://docs.sentry.io/clients/react-native/manual-setup/ I see what needs done I think under "Upload Debug Symbols to Sentry" at least for iOS (it missing Android instructions).

```
If you wish to upload the source maps and symbols to Sentry, create a new Run Script build phase with the following script:

export SENTRY_PROPERTIES=../sentry.properties

../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

**Comment by jeremybarbet** [comment]
Hi! I will close this, since we upgrade the starter and we are now using latest version of sentry that have different integration
