### ISSUE TITLE
Detox Issues with Xcode 10.2

### ISSUE THREAD

**Issue by Amosel** [ueno-llc/react-native-starter#218]
**Describe the bug**
Xcode 10.2 doesn't support the Swift Language Version that comes with the current Detox 10.0.12

corresponding Detox issue: https://github.com/wix/Detox/issues/1229

**To Reproduce**

With XCode 10.2 installed:

`git clone git@github.com:ueno-llc/react-native-starter.git my-new-app`
`cd my-new-app`
`yarn`

**Expected behavior**
Post install script for Detox should run successfully.

### Environment
* React Native Starter version: [2.1.0]
* React Native version: [0.59.0-rc.3]
* Platforms
  * [X] iOS
  * [ ] Android
* Device Info
  * [ ] Physical Device in Debug
  * [ ] Physical Device in Release
  * [ ] Simulator in Debug
  * [ ] Simulator in Release

### Device and Verbose Detox Logs

```
=== BUILD TARGET Detox OF PROJECT Detox WITH CONFIGURATION Release ===

Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by birkir** [comment]
Fixed with v3.0.0
