### ISSUE TITLE
Hot Reloading not working

### ISSUE THREAD

**Issue by dmkmedina** [ueno-llc/react-native-starter#219]
Hey guys, thanks so much for a such an awesome starter. Easily the best one I've seen.

**Describe the bug**
Hot reloading appears to not be functional on the latest version of the project. When changes are made, the "Hot Loading" message appears, but the changes are not visible.

**To Reproduce**
1. Clone Repo
2. Follow setup instructions in the docs
3. Run project on an ios simulator
4. Turn on hot reloading
5. Make a change to the Home screen

**Expected behavior**
Making changes to the Home screen with Hot Reloading enabled should be visible without a manual reload.

### Environment
* React Native Starter version:  v2.2.0
* React Native version: 0.59.0-rc.3
* Platforms
  * [x] iOS
  * [ ] Android
* Device Info
  * [ ] Physical Device in Debug
  * [ ] Physical Device in Release
  * [x] Simulator in Debug
  * [ ] Simulator in Release

### Additional context

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
      Memory: 1.53 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.0, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.3
        API Levels: 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.8.7 => 16.8.7 
      @types/react-native: 0.57.38 => 0.57.38 
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.0-rc.3 => 0.59.0-rc.3

**Comment by jeremybarbet** [comment]
H!

Yes you are totally right, Hot reload is not working. We don't use it that much (at least me), so I didn't even notice it. I upgraded packages but it didn't change anything.

It's something related to our setup. We would need to dig in to find the issue. If you have time you can try to look for the issue. 

Thanks!

**Comment by birkir** [comment]
I will take a look

**Comment by dylmye** [comment]
Can't test with macOS or iOS, does turning on Live Reload _and_ Hot Reload make any difference?

**Comment by birkir** [comment]
Fixed in [v3.0.0](https://github.com/ueno-llc/react-native-starter/releases/tag/v3.0.0)
