### ISSUE TITLE
./scripts/rename.sh: line 108: ./scripts/build-env.sh: No such file or directory

### ISSUE THREAD

**Issue by ViralS-Truongnh** [ueno-llc/react-native-starter#231]
**Describe the bug**
init project from ueno-app native fail 

**To Reproduce**
1 clone or init ueno-app from yarn create always have error: ./scripts/rename.sh: line 108: ./scripts/build-env.sh: No such file or directory

in rename step.

**Expected behavior**
just wanna create a project from ueno-app react native starter

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

### Environment
* React Native Starter version: lastest version (5/2/2020)
* React Native version: 0.62.0-rc1

### Additional context

I think this bug is very clear. when i check line 108 in ./scripts/rename.sh. this line invoke a file that doesn't exist.
Please check out and fix this. I love this project so much, but not have enough knowledge in react native and nativ to pull request and fix right now.

**Comment by birkir** [comment]
Fixed 👍
