### ISSUE TITLE
Doesn't start the packager process when running

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/react-native-starter#24]
Is there any reason we shouldn't add a `yarn start` command when the app builds?

**Comment by birkir** [comment]
Can you add some clarity to your question? Are you talking about starting metro when you run `react-native run-ios` or `react-native run-android`?

Currently, we start the metro bundler in a separate session than where we build the app for each platform. This is something that stopped working on iOS for some reason, and the bundler react-native run-android starts is having trouble with resolving the import root.
