### ISSUE TITLE
bug RCTText

### ISSUE THREAD

**Issue by nova974** [ueno-llc/react-native-starter#40]
I think you should upgrade react-native version to 0.53.3
I've got problems with RCTText component with version 0.53.0

**Comment by birkir** [comment]
You are right. We will branch into develop for the future, so master will be in sync with latest release.

We upgraded to 0.54 but had to downgrade, and choose incorrect version.

The [latest release](https://github.com/ueno-llc/react-native-starter/tree/v1.0.2) has 0.53.3 (also fixed on master with https://github.com/ueno-llc/react-native-starter/commit/f9b3d814cd53b219a532d98ce87634d86d202cce)
