### ISSUE TITLE
Can't link external libraries

### ISSUE THREAD

**Issue by elliottkember** [ueno-llc/react-native-starter#6]
```➜  UenoDesign2 git:(master) ✗ react-native link
Scanning folders for symlinks in /Users/elliott/ueno/UenoDesign2/node_modules (14ms)
rnpm-install info Linking react-native-browser ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Invalid target: E3AAD4501F573E3700B7831D
Please file an issue here: https://github.com/facebook/react-native/issues

Invalid target: E3AAD4501F573E3700B7831D
```

Manually linking doesn't work either - `no native component found for FastImageView`.

**Comment by birkir** [comment]
You need Podspec for ios modules, you can copy and modify one of the included file in ./scripts/patches and then add it to the postinstall script.

This is one of the things we need to document.

Reason why I do it this way is because it's not as fragile as react-native link

**Comment by elliottkember** [comment]
OK, good to know. I’ll try this out and add a section to the readme once I figure it out.

**Comment by isaachinman** [comment]
@elliottkember Do you plan to add this to the docs?

**Comment by birkir** [comment]
https://ueno-llc.github.io/react-native-starter/#/INSTALL_DEPENDENCIES
