### ISSUE TITLE
Deep linking support?

### ISSUE THREAD

**Issue by isaachinman** [ueno-llc/react-native-starter#67]
Hi there, I previously commented on an open issue so you might remember my face! I've decided to take the plunge and am using this starter kit as the launching point for my first RN build. So far I am really enjoying the codebase and the opinionated decisions that have been made.

I'm new to RN, so you'll have to excuse me if I'm missing something very obvious, but it looks like this starter kit does not support any kind of deep linking out of the box, is that right?

Of course, `react-native-navigation` has its own `setOnNavigatorEvent` for deep linking, but out of the box I can't see a way to actually add a linking scheme to this ueno kit.

If that's correct, I'll proceed manually with [react-native-deep-linking](https://www.npmjs.com/package/react-native-deep-linking) (or similar). Might be worth opening a feature request, as I imagine almost all RN projects need this.

**Comment by birkir** [comment]
Hi Isaac, this is a very good question.

We haven't opinionated a deep linking services like Branch.io or AppBoy (now Braze).

We do however have Firebase, that has something called Dynamic Links. It's just not configured by default.

I will take a look at react-native-deep-linking and see if it would make more sense than the react-native-navigation method.

The outcome of this task should at least lead to the documentation.

Thanks!

**Comment by isaachinman** [comment]
Another thing to consider - where is the base URI scheme defined? Are changes to this covered in your `rename.sh` script?

**Comment by isaachinman** [comment]
@birkir Not to keep bumping this thread, but it also seems that `Linking.getInitialURL()` returns `null` in this starter kit.

**Comment by birkir** [comment]
No, this is something that we won't ship by default (yet).

**Comment by isaachinman** [comment]
Okay, understood.

For what it's worth (and for anyone reading in the future), I have so far been able to handle all my deep linking needs via `react-native-navigation` after a few small changes to `AndroidManifest.xml` and `Info.plist`, etc.

I think it would be trivial to include this functionality by default (probably less than 30 lines), and automatically change URI in the `rename` script. Just my opinion!

**Comment by birkir** [comment]
Sweet! (I am happy to accept pull requests)

**Comment by isaachinman** [comment]
[PR created.](https://github.com/ueno-llc/react-native-starter/pull/78)
