### ISSUE TITLE
Bitrise.yml

### ISSUE THREAD

**Issue by respectTheCode** [ueno-llc/react-native-starter#71]
It would be great to see how you have bitrise configured.

**Comment by birkir** [comment]
Hey! Good idea, I'll share my yml here so you can get started quickly and I'll add it to the docs later!

https://gist.github.com/birkir/e4b973ebdbee09e2731c724b5e20b46f

It's a bit messy, but hope it will get you going.

**Comment by respectTheCode** [comment]
Do you have separate apps in bitrise for android and iOS?

**Comment by birkir** [comment]
Yes, it could be combined, but i like having them run in parallel.

**Comment by brianjd** [comment]
@birkir That being said, do you have separate projects in Sentry for each platform?

**Comment by birkir** [comment]
No, I only have one with hybrid stack traces.

**Comment by isaachinman** [comment]
@birkir Do you plan to add Bitrise info to the docs anytime soon? New RN dev here trying to navigate the complex world of publishing...

**Comment by isaachinman** [comment]
Also @birkir, if you're running two separate Bitrise projects for one repo, how do you keep webhook triggers from entering an infinite loop?

**Comment by birkir** [comment]
The release commit message includes "[skip ci]" which most CI runners should understand.

https://github.com/ueno-llc/react-native-starter/blob/develop/ios/fastlane/Fastfile#L61

**Comment by isaachinman** [comment]
Ah, didn't see that. Thanks. Let me know if there's anything I can do to help improve the CI docs here.

**Comment by jeremybarbet** [comment]
I close this issue. We've been rewriting the documentation a lot lately.

We are now using App Center for publishing and Continuous delivery. To keep it clear and simple we don't have any documentation for Bitrise, fastlane or travis. If there is a need for that we could look for it later.
