### ISSUE TITLE
Is this project compatible with react-native-fetch-blob?

### ISSUE THREAD

**Issue by isaachinman** [ueno-llc/react-native-starter#81]
This might be a more general cocoapods issue, but I've tried to install the very popular [react-native-fetch-blob](https://github.com/joltup/react-native-fetch-blob) package, and dependencies don't appear to be shared into that codebase, despite their having a `podspec`.

What else needs to be done? Is this a header search paths issue? Is it necessary to somehow patch dependencies that _do_ have podspecs as well?

**Comment by isaachinman** [comment]
**Update:** I actually did manage to install RNFetchBlob quite easily, but there's a really strange import error outlined in [this issue](https://github.com/wkh237/react-native-fetch-blob/issues/685). Basically, I am forced to import the module during runtime instead of at launch/build. No idea why, yet.

**Comment by birkir** [comment]
Looks like a issue with RNFetchBlob.

If you still think this is an issue with RNS, reopen this ticket 👍
